// Regenerates src/lib/abi.ts from the Foundry build output (run `forge build` first).
import { readFileSync, writeFileSync } from "node:fs";

const out = new URL("../../contracts/out/", import.meta.url);
const abi = (path) => JSON.parse(readFileSync(new URL(path, out), "utf8")).abi;

const body = [
  "// Generated by `npm run abi` from contracts/out. Do not edit by hand.",
  "",
  `export const trustAbi = ${JSON.stringify(abi("KinfolioTrust.sol/KinfolioTrust.json"), null, 2)} as const;`,
  "",
  `export const factoryAbi = ${JSON.stringify(abi("KinfolioFactory.sol/KinfolioFactory.json"), null, 2)} as const;`,
  "",
].join("\n");

writeFileSync(new URL("../src/lib/abi.ts", import.meta.url), body);
console.log("wrote src/lib/abi.ts");
