[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.30"
evm_version = "cancun"
optimizer = true
optimizer_runs = 10_000
bytecode_hash = "none"
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/",
]

[profile.default.fuzz]
runs = 1_000

[profile.default.invariant]
runs = 256
depth = 64
fail_on_revert = false

[profile.ci.fuzz]
runs = 10_000

[rpc_endpoints]
robinhood_testnet = "https://rpc.testnet.chain.robinhood.com"
robinhood = "https://rpc.mainnet.chain.robinhood.com"

[etherscan]
robinhood_testnet = { key = "blockscout", chain = 46630, url = "https://explorer.testnet.chain.robinhood.com/api" }
robinhood = { key = "blockscout", chain = 4663, url = "https://robinhoodchain.blockscout.com/api" }

[fmt]
line_length = 100
